### ISSUE TITLE
Missing purge method on Unity 

### ISSUE THREAD

**Issue by 00christian00** [soomla/soomla-unity3d-core#17]
I was looking for a way to reset the db and noticed the native class has a purge method, but it is not exposed in the plugin. Can you please add it ?

**Comment by refaelos** [comment]
@vedi @borisspektor are we working on the 'reset' functions?

**Comment by borisspektor** [comment]
@refaelos yes we are

**Comment by EugeneButusov** [comment]
@vedi @borisspektor @refaelos 
I looked into bridges at crossplatform engines.
incoming Unity3D implementation: https://github.com/vedi/soomla-unity3d-core/pull/6
Cocos2dx doesn't use KVS via bridges so changes isn't required.

**Comment by borisspektor** [comment]
@00christian00 the purge method is now available. Please download the latest release.
Closing this issue.
