### ISSUE TITLE
soomla unity android public key confusion.

### ISSUE THREAD

**Issue by rsamrry** [soomla/soomla-unity3d-core#49]
hi,
So i am guessing that the _public key_ mentioned in the soomla docs refers to the _API Key_ in the unity editor in the soomla window. 
my question is : should this be the same as the _Licence Key_ from the _Services and APIs_ section in the google play developers console?
If not, then what?
I am using the latest soomla(Paid version) for IAPs and using unity ver 5.3.2(free version)
Thank you,
Sameer Raina

**Comment by EugeneButusov** [comment]
@rsamrry, could you please clarify it with screenshot what value do you mean?

**Comment by rsamrry** [comment]
Hi,
@EugeneButusov, in unityscreenshot, you will see a box for api key under google play. i just want to know what goes in there. currently i have in it the value at the bottom of the screen of googleplayconsolescreenshot.
thanks,
rsamrry




![googleplayconsolescreenshot](https://cloud.githubusercontent.com/assets/4905026/15820945/5f16b714-2c0a-11e6-8572-977f4189b40c.png)
![unityscreenshot](https://cloud.githubusercontent.com/assets/4905026/15820946/5f4da0a8-2c0a-11e6-9903-f68c50a8bd1f.png)

**Comment by EugeneButusov** [comment]
@rsamrry, yeah, you placed api key in correct place.
