### ISSUE TITLE
How to link project between developers.google.com and google play

### ISSUE THREAD

**Issue by rsamrry** [soomla/soomla-unity3d-core#50]
Hi,
I have created a project in console.developers.google.com and another one in the google play developers console. Both projects have the same name. does that mean they are automatically linked or do i have to do something to link them. i have enabled an api i want to use in my game but in the google play console i haven't uploaded any apk cos i haven't configured my soomla yet.
please help.
thanks,
sameer raina

**Comment by EugeneButusov** [comment]
@rsamrry, you can find anwer there: https://developers.google.com/android-publisher/getting_started#linking_your_api_project

**Comment by rsamrry** [comment]
@EugeneButusov , thank you very much.
rsamrry
