### ISSUE TITLE
Reference class members 'Rewards' instead of ctor parameter 'rewards' in RandomRewards and SequenceRewards ctors

### ISSUE THREAD

**Issue by LeshM** [soomla/soomla-unity3d-core#7]
public List<Reward> Rewards;

public SequenceReward(string id, string name, List<Reward> rewards) : base(id, name)
{
	if ((Rewards == null || Rewards.Count == 0)) {
		SoomlaUtils.LogError(TAG, "This reward doesn't make sense without items");
	}
	Rewards = rewards;
}

**Comment by refaelos** [comment]
Good Catch. Can you fix and pull-request it?

**Comment by LeshM** [comment]
There you go: https://github.com/soomla/soomla-unity3d-core/pull/8

**Comment by refaelos** [comment]
Thanks. Merged! :+1:
